app:
    transformers:
        calculate: App\Transformer\CalculateTransformer
        expand_key: ExpandKeyTransformer
        filter: FilterTransformer
        select_names: App\Transformer\SelectNamesTransformer
        replace: App\Transformer\ReplaceTransformer
