easy_admin:
    entities:
        User:
            class: App\Entity\User

        DataSource:
           class: App\Entity\DataSource

           list:
               fields:
                   - property: name
                   - property: url
                   - property: type

           form:
               fields:
                   - property: name
                   - property: url
                   - property: type

        DataWrangler:
            class: App\Entity\DataWrangler
            controller: App\Controller\DataWranglerController

            list:
                actions: [run]

                fields:
                    - property: name
                    - property: dataSources
                    - property: transforms

            form:
                fields:
                    - property: name
                    - property: dataSources
                    - property: transforms
                      type: collection
                      type_options:
                            entry_type: App\Form\Type\DataTransformType
                            allow_delete: true
                            allow_add: true
                            by_reference: false
