fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: 'App\Entity\User'
    from_email:
        address: '%mailer_from_email%'
        sender_name: '%mailer_from_name%'

    service:
        user_manager: ItkDev\UserManagementBundle\Doctrine\UserManager
        mailer: fos_user.mailer.twig_swift
